#!/usr/bin/env bash
# Funcion para cambiar el wallpaper aleatoriamente
function rand_wall (){
  dir='/home/gibranlp/Pictures/wallPapers/dark'
   wal -i "${dir[RANDOM % ${#dir[@]}]}" -q 
}
rand_wall &
qtile-cmd -o cmd -f restart &