#!/bin/sh
# Funcion para cambiar el wallpaper aleatoriamente
function rand_wall (){
  dir='/home/gibranlp/Pictures/wallPapers/white'
    wal --backend haishoku -i "${dir[RANDOM % ${#dir[@]}]}" -q -l  &
}
rand_wall &
qtile-cmd -o cmd -f restart &