#!/bin/bash

rofi_command="rofi"

## Get info
IFACE="$(nmcli | grep -i interface | awk '/interface/ {print $2}')"
SSID="$(iwgetid -r)"
LIP="$(nmcli | grep -i server | awk '/server/ {print $2}')"
#PIP="$(dig +short myip.opendns.com @resolver1.opendns.com )"
STATUS="$(nmcli radio wifi)"

active=""
urgent=""

if (ping -c 1 archlinux.org || ping -c 1 google.com ) &>/dev/null; then
	if [[ $STATUS == *"enable"* ]]; then
        if [[ $IFACE == e* ]]; then
            connected="[-] Not Connected"
        else
            connected="[*] Connection Extablished"
        fi
	active="-a 0"
	SSID="$(iwgetid -r)"
	PIP="$(wget --timeout=30 http://ipinfo.io/ip -qO -)"
	fi
else
    urgent="-u 0"
    SSID="Disconnected"
    PIP="NA"
    connected=" Offline"
fi

## Icons
bmon="[+] Open Bandwidth Monitor"
launch_cli="[+] Open Network Manager"
launch="[+] Open Connection Editor"

options="$connected\n$bmon\n$launch_cli\n$launch"

## Main
chosen="$(echo -e "$options" | $rofi_command -p "$SSID : $PIP" -dmenu $active $urgent -selected-row 0)"
case $chosen in
    $connected)
		if [[ $STATUS == *"enable"* ]]; then
			nmcli radio wifi off
		else
			nmcli radio wifi on
		fi 
        ;;
    $bmon)
        urxvt -e bmon
        ;;
    $launch_cli)
        urxvt -e nmtui
        ;;
    $launch)
        nm-connection-editor
        ;;
esac

