--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/gibranlp/Cloud/wallPapers/wallhaven-eymzjk.jpg"

-- Special
background="#371220"
foreground="#a8d9d9"
cursor="#a8d9d9"

-- Colors
color0="#371220"
color1="#617489"
color2="#C1778A"
color3="#178D8E"
color4="#2F8B8C"
color5="#4F9391"
color6="#659E9E"
color7="#a8d9d9"
color8="#759797"
color9="#617489"
color10="#C1778A"
color11="#178D8E"
color12="#2F8B8C"
color13="#4F9391"
color14="#659E9E"
color15="#a8d9d9"
