# Shell variables
# Generated by 'wal'
wallpaper='/home/gibranlp/Cloud/wallPapers/wallhaven-eymzjk.jpg'

# Special
background='#371220'
foreground='#a8d9d9'
cursor='#a8d9d9'

# Colors
color0='#371220'
color1='#617489'
color2='#C1778A'
color3='#178D8E'
color4='#2F8B8C'
color5='#4F9391'
color6='#659E9E'
color7='#a8d9d9'
color8='#759797'
color9='#617489'
color10='#C1778A'
color11='#178D8E'
color12='#2F8B8C'
color13='#4F9391'
color14='#659E9E'
color15='#a8d9d9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
